services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data
    env_file:
      - ${ENV_FILE}
    networks:
      - app_network

  backend:
    image: openjdk:25-jdk
    build: ./backend/online_booking_app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    image: node:22-alpine
    build: ./frontend/online-booking-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - postgres
    volumes:
     - ./frontend/online-booking-ui:/app
     - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev
    networks:
      - app_network

volumes:
  db_data:
  node_modules:

networks:
  app_network:
    driver: bridge