spring:
    config:
        import: file:.env[.properties]
    datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: ${DB_URL}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    sql:
        init:
            mode: always
            continue-on-error: true