name: Online Booking Spring Boot Backend CI

on:
  push:
    branches:
      - main # or your main development branch
    paths:
      - 'backend/**' # Trigger only on changes in the backend directory

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: bookings_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postpass
        ports:
          - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.1.4
        with:
          path: ./backend/online_booking_app/.env

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25' # or your desired Java version
          distribution: 'zulu' # or another distribution like 'adopt'

      - name: Build with Maven
        run: mvn clean install -DskipTests # Build the project, skip tests for faster build in CI
        working-directory: ./backend/online_booking_app

      - name: Build and start Docker Compose services
        run: docker compose up -d --build

      - name: Run Tests
        run: mvn test # Run tests separately
        working-directory: ./backend/online_booking_app
    
