name: Online Booking Spring Boot Backend CI

on:
  push:
    branches:
      - main # or your main development branch
    paths:
      - 'backend/**' # Trigger only on changes in the backend directory

jobs:
  configure-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.1.4
        with:
          path: ./backend/online_booking_app/.env

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25' # or your desired Java version
          distribution: 'zulu' # or another distribution like 'adopt'
    
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{env.DB_NAME}}
          POSTGRES_USER: ${{env.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Build with Maven
        run: mvn clean install -DskipTests # Build the project, skip tests for faster build in CI
        working-directory: ./backend/online_booking_app

      - name: Run Tests
        run: mvn test # Run tests separately
        working-directory: ./backend/online_booking_app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/online_booking_app
          push: false
    
